Feature1 hello
vancuongngo/test-github-bot pull request #2
Opened 2021-06-01 19:40 UTC by vancuongngo

hello

2021-07-26 14:27 UTC, vancuongngo commented on README.md
> +commit 1
a comment on add commit 1

2021-07-26 14:28 UTC, vancuongngo commented on README.md
> +commit 1
another one

2021-07-26 14:36 UTC, vancuongngo commented on README.md
> +commit 1
another two

2021-07-26 14:45 UTC, vancuongngo commented on README.md
> +# test-github-bot
another three

2021-07-26 14:58 UTC, vancuongngo commented on README.md
> +# test-github-bot
another four

2021-07-26 14:59 UTC, vancuongngo commented on README.md
> +# test-github-bot
another five

2021-07-26 15:00 UTC, vancuongngo commented on README.md
> +# test-github-bot
another six

2021-07-26 15:06 UTC, vancuongngo commented on README.md
> +# test-github-bot
another seven

2021-07-26 15:10 UTC, vancuongngo commented on README.md
> +# test-github-bot
another eight

2021-07-26 15:11 UTC, vancuongngo commented on README.md
> +# test-github-bot
another nine

2021-07-26 15:11 UTC, vancuongngo commented on README.md
> +# test-github-bot
another ten

2021-07-26 15:51 UTC, vancuongngo commented on README.md
> +# test-github-bot
eleven

2021-07-26 15:52 UTC, vancuongngo commented on README.md
> +# test-github-bot
eleven

2021-07-28 08:32 UTC, cuongngo-kry requested changes
please change

2021-07-28 08:32 UTC, cuongngo-kry commented on README.md
> +# test-github-bot
one

2021-07-28 08:32 UTC, cuongngo-kry commented on README.md
> +commit 1
two

2021-07-28 08:33 UTC, cuongngo-kry commented on README.md
> +commit 1
three

2021-07-28 08:33 UTC, cuongngo-kry commented on README.md
> +commit 1
four

2021-07-28 08:36 UTC, cuongngo-kry commented on README.md
> +commit 1
five

2021-07-28 08:37 UTC, cuongngo-kry commented on README.md
> +commit 1
six

2021-07-28 08:38 UTC, cuongngo-kry commented on README.md
> +commit 1
seven

2021-07-28 08:40 UTC, cuongngo-kry commented on README.md
> +commit 1
eight

2021-07-28 08:43 UTC, cuongngo-kry reviewed
hello

2021-07-28 08:43 UTC, cuongngo-kry commented on README.md
> +commit 1
nine

2021-07-28 08:43 UTC, cuongngo-kry commented on README.md
> +# test-github-bot
two

2021-07-28 08:46 UTC, cuongngo-kry approved these changes
ok

2021-07-28 08:50 UTC, cuongngo-kry requested changes
hoho

2021-07-28 08:50 UTC, cuongngo-kry approved these changes
ok

2021-07-28 08:56 UTC, cuongngo-kry commented on README.md
> +# test-github-bot
three

2021-07-28 08:58 UTC, cuongngo-kry commented on README.md
> +# test-github-bot
four

2021-07-28 09:01 UTC, cuongngo-kry commented on README.md
> +# test-github-bot
five

2021-07-28 09:02 UTC, cuongngo-kry commented on README.md
> +# test-github-bot
six

2021-07-28 09:11 UTC, vancuongngo commented
reopen pr

2021-07-28 09:21 UTC, vancuongngo commented
close it

2021-07-28 09:21 UTC, vancuongngo commented
another chance

2021-07-28 09:25 UTC, merged